import = ["~/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"

[window.padding]
x = 5
y = 15

[font]
size = 10.5

[font.normal]
family = "Iosevka Term"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "Return"
mods = "Control"
