import = ["~/.config/alacritty/tokyonight-night.toml"]

[env]
# Ensures undercurl works inside tmux and neovim.
# See: https://github.com/neovim/neovim/issues/21182
# See: https://github.com/alacritty/alacritty/issues/6149
# See: https://github.com/alacritty/alacritty/issues/6802
TERM = "alacritty"

[window]
decorations = "None"

[window.padding]
x = 5
y = 15

[font]
size = 10.5

[font.normal]
family = "Iosevka Term"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "Return"
mods = "Control"
