[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']
screensaver=@as []

[custom-keybindings/custom0]
binding='<Alt>Return'
command='alacritty'
name='Terminal'

[custom-keybindings/custom1]
binding=''
command='gauntlet'
name='Gauntlet'
